#!/bin/bash

# Define variables
BUSINESS_NAME="Your Business Name"
LOGO_SRC="your_logo_source_url"
EMPLOYEE_NAME="Employee Name"
EMPLOYEE_EMAIL="employee@example.com"
EMPLOYEE_TITLE="Employee Title"
STORE_ADDRESS="1234 Business St, City, State ZIP"
STORE_PHONE="123-456-7890"
FACEBOOK_URL="https://www.facebook.com/yourpage"
FACEBOOK_IMG_SRC="your_facebook_image_source_url"
INSTAGRAM_URL="https://www.instagram.com/yourpage"
INSTAGRAM_IMG_SRC="your_instagram_image_source_url"
PINTEREST_URL="https://www.pinterest.com/yourpage"
PINTEREST_IMG_SRC="your_pinterest_image_source_url"
YOUTUBE_URL="https://www.youtube.com/yourchannel"
YOUTUBE_IMG_SRC="your_youtube_image_source_url"

# Create the HTML content
HTML_CONTENT="<html>
<body>
	<div>
		<h5>Kind Regards</h5>
	</div>
	<div dir=\"ltr\">
		<table cellpadding=\"0\" cellspacing=\"0\" style=\"vertical-align:-webkit-baseline-middle;font-family:Georgia\">
			<tbody>
				<tr>
					<td style=\"vertical-align:middle\">
						<table cellpadding=\"0\" cellspacing=\"0\" style=\"vertical-align:-webkit-baseline-middle;font-family:Georgia\">
							<tbody>
								<tr>
									<td style=\"text-align:center\">
										<a href=\"#\" target=\"_blank\"><img src=\"$LOGO_SRC\" style=\"max-width:90px;display:block\"></a>
									</td>
								</tr>
							</tbody>
						</table>
					</td>
					<td width=\"15\"></td>
					<td style=\"padding:0px;vertical-align:middle\">
						<h3 color=\"#000000\" style=\"margin:0px;font-size:16px;color:rgb(0,0,0)\">
							<table cellpadding=\"0\" cellspacing=\"0\" style=\"font-weight:normal;font-family:Georgia\">
								<tbody>
									<tr>
										<td style=\"line-height:1.08\">
											<span style=\"font-size:12px;font-family:Georgia;font-weight:bold\">$EMPLOYEE_NAME</span>
											<span style=\"font-size:12px;letter-spacing:0px;font-family:Georgia;text-transform:initial\">$EMPLOYEE_TITLE</span>
											<span style=\"font-size:12px;letter-spacing:0px;font-family:Georgia;text-transform:initial\">at $BUSINESS_NAME</span>
										</td>
									</tr>
									<tr>
										<td style=\"line-height:0;padding-top:10px;padding-bottom:10px\">
											<table cellspacing=\"0\" cellpadding=\"0\" style=\"width:387px\">
												<tbody>
													<tr>
														<td style=\"line-height:0;font-size:1pt;border-bottom-width:2px;border-bottom-style:solid;border-bottom-color:rgb(0,0,0)\"></td>
													</tr>
												</tbody>
											</table>
										</td>
									</tr>
									<tr>
										<td style=\"line-height:0\">
											<table cellpadding=\"0\" cellspacing=\"0\">
												<tbody>
													<tr>
														<td>
															<table cellpadding=\"0\" cellspacing=\"0\">
																<tbody>
																	<tr>
																		<td style=\"line-height:0px;padding-bottom:4px\">
																			<table cellpadding=\"0\" cellspacing=\"0\" style=\"line-height:14px;font-size:12px;font-family:Georgia\">
																				<tbody>
																					<tr>
																						<td style=\"font-family:Georgia\">
																							<a href=\"tel:$STORE_PHONE\" style=\"text-decoration:none\" target=\"_blank\"><span style=\"line-height:1.2;color:rgb(33,33,33);white-space:nowrap\">$STORE_PHONE</span></a>
																						</td>
																					</tr>
																				</tbody>
																			</table>
																		</td>
																		<td style=\"line-height:0px;padding-bottom:4px\">
																			<table cellpadding=\"0\" cellspacing=\"0\" style=\"line-height:14px;font-size:12px;font-family:Georgia\">
																				<tbody>
																					<tr>
																						<td style=\"padding:0px 4px\">
																							<span style=\"font-family:Georgia;font-weight:bold;color:rgb(33,33,33);vertical-align:2px\">|</span>
																						</td>
																						<td style=\"font-family:Georgia\">
																							<a href=\"#\" style=\"text-decoration:none\" target=\"_blank\"><span style=\"line-height:1.2;color:rgb(33,33,33);white-space:nowrap\">$BUSINESS_NAME</span></a>
																						</td>
																					</tr>
																				</tbody>
																			</table>
																		</td>
																		<td style=\"line-height:0px;padding-bottom:4px\">
																			<table cellpadding=\"0\" cellspacing=\"0\" style=\"line-height:14px;font-size:12px;font-family:Georgia\">
																				<tbody>
																					<tr>
																						<td style=\"padding:0px 4px\">
																							<span style=\"font-family:Georgia;font-weight:bold;color:rgb(33,33,33);vertical-align:2px\">|</span>
																						</td>
																						<td style=\"font-family:Georgia\">
																							<a href=\"mailto:$EMPLOYEE_EMAIL\" style=\"text-decoration:none\" target=\"_blank\"><span style=\"line-height:1.2;color:rgb(33,33,33);white-space:nowrap\">$EMPLOYEE_EMAIL</span></a>
																						</td>
																					</tr>
																				</tbody>
																			</table>
																		</td>
																	</tr>
																</tbody>
															</table>
														</td>
													</tr>
													<tr>
														<td>
															<table cellpadding=\"0\" cellspacing=\"0\">
																<tbody>
																	<tr>
																		<td style=\"line-height:0px;padding-bottom:4px\">
																			<table cellpadding=\"0\" cellspacing=\"0\" style=\"line-height:14px;font-size:12px;font-family:Georgia\">
																				<tbody>
																					<tr>
																						<td style=\"font-family:Georgia\">
																							<span style=\"line-height:1.2;color:rgb(33,33,33);white-space:nowrap\">$STORE_ADDRESS</span>
																						</td>
																					</tr>
																				</tbody>
																			</table>
																		</td>
																	</tr>
																</tbody>
															</table>
														</td>
													</tr>
												</tbody>
											</table>
										</td>
									</tr>
								</tbody>
							</table>
						</h3>
						<a href=\"$FACEBOOK_URL\" target=\"_blank\"><img width=\"22\" height=\"22\" src=\"$FACEBOOK_IMG_SRC\" border=\"0\" style=\"border:none; margin:15px\"></a>
						<a href=\"$INSTAGRAM_URL\" target=\"_blank\"><img width=\"22\" height=\"22\" src=\"$INSTAGRAM_IMG_SRC\" border=\"0\" style=\"border:none; margin:15px\"></a>
						<a href=\"$YOUTUBE_URL\" target=\"_blank\"><img width=\"22\" height=\"22\" src=\"$YOUTUBE_IMG_SRC\" border=\"0\" style=\"border:none; margin:15px\"></a>
						<a href=\"$PINTEREST_URL\" target=\"_blank\"><img width=\"22\" height=\"22\" src=\"$PINTEREST_IMG_SRC\" border=\"0\" style=\"border:none; margin:15px\"></a>
					</td>
				</tr>
			</tbody>
		</table>
		<br>
	</div>
</body>
</html>"

# Save the content to an HTML file
echo "$HTML_CONTENT" > signature.html
